// Мокап данные для GitHub Pages

export const mockUsers = {
  petowner: {
    id: 1,
    profile_id: 1,
    username: 'petowner',
    email: 'owner@vetcard.com',
    role: 1,
    first_name: 'Иван',
    last_name: 'Петров',
    third_name: 'Сергеевич',
    phone: '+996 (555) 123-45-67',
    city: 'Бишкек',
    address: 'ул. Чуй, д. 123',
  },
  veterinarian: {
    id: 2,
    profile_id: 2,
    username: 'veterinarian',
    email: 'vet@vetcard.com',
    role: 2,
    first_name: 'Мария',
    last_name: 'Иванова',
    third_name: 'Александровна',
    phone: '+996 (555) 234-56-78',
    city: 'Бишкек',
    address: 'ул. Ленина, д. 45',
    clinic: "Ветеринарная клиника 'Здоровье'",
    position: 'Главный ветеринар',
    specialization: 'Мелкие животные',
    experience: '10 лет',
    license_number: 'VET-KG-2024-001',
    description: 'Опытный ветеринар с многолетним стажем работы. Специализация на лечении собак и кошек.',
  },
  partner: {
    id: 3,
    profile_id: 3,
    username: 'partner',
    email: 'partner@vetcard.com',
    role: 3,
    first_name: 'ООО',
    last_name: 'ЗооМаркет',
    city: 'Бишкек',
    address: 'ул. Советская, д. 78',
    name_of_organization: 'ЗооМаркет',
    type: 'Зоомагазин',
    phone: '+996 (555) 345-67-89',
    website: 'https://zoomarket.kg',
    description: 'Крупнейший зоомагазин в Бишкеке. Полный ассортимент кормов, игрушек и аксессуаров для животных.',
  },
  admin: {
    id: 4,
    profile_id: 4,
    username: 'admin',
    email: 'admin@vetcard.com',
    role: 4,
    first_name: 'Администратор',
    last_name: 'Системы',
    phone: '+996 (555) 000-00-00',
    city: 'Бишкек',
  },
};

export const mockPets = [
  {
    id: '1',
    name: 'Рекс',
    species: 1,
    breed: 'Немецкая овчарка',
    birth_date: '2020-01-15',
    weight: 32.5,
    image_url: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=400',
    special_notes: 'Активный, любит играть на улице. Аллергия на курицу.',
    user: 1,
  },
  {
    id: '2',
    name: 'Мурка',
    species: 2,
    breed: 'Британская короткошерстная',
    birth_date: '2021-05-20',
    weight: 4.2,
    image_url: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400',
    special_notes: 'Спокойная, любит спать. Нужен специальный корм для чувствительного желудка.',
    user: 1,
  },
  {
    id: '3',
    name: 'Чарли',
    species: 3,
    breed: 'Волнистый попугай',
    birth_date: '2022-03-10',
    weight: 0.05,
    image_url: 'https://images.unsplash.com/photo-1452570053594-1b985d6ea890?w=400',
    special_notes: 'Очень общительный, любит петь.',
    user: 1,
  },
];

export const mockAnimalTypes = [
  { id: 1, name_ru: 'Собака', name_kg: 'Ит', is_active: true },
  { id: 2, name_ru: 'Кошка', name_kg: 'Мышык', is_active: true },
  { id: 3, name_ru: 'Птица', name_kg: 'Куш', is_active: true },
  { id: 4, name_ru: 'Грызун', name_kg: 'Кемирүүчүлөр', is_active: true },
  { id: 5, name_ru: 'Рептилия', name_kg: 'Рептилия', is_active: true },
];

export const mockArticles = [
  {
    id: 1,
    title: 'Уход за собакой в зимний период',
    excerpt: 'Зима - особое время для наших питомцев. Узнайте, как правильно ухаживать за собакой в холодное время года, защитить лапы от реагентов и обеспечить комфорт в морозную погоду.',
    image_url: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=800',
    category: 'Уход',
    published_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    author: {
      name: 'Доктор Иванов',
      avatarUrl: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    source_url: 'https://example.com/article1',
  },
  {
    id: 2,
    title: 'Правильное питание кошек',
    excerpt: 'Сбалансированное питание - основа здоровья вашей кошки. Читайте о правильном рационе для домашних кошек, режиме кормления и выборе качественного корма.',
    image_url: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800',
    category: 'Питание',
    published_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    author: {
      name: 'Ветеринар Петрова',
      avatarUrl: 'https://randomuser.me/api/portraits/women/2.jpg',
    },
    source_url: 'https://example.com/article2',
  },
  {
    id: 3,
    title: 'График прививок для щенков',
    excerpt: 'Вакцинация - важнейшая часть заботы о здоровье щенка. Узнайте о графике прививок, необходимых вакцинах и подготовке к процедуре.',
    image_url: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800',
    category: 'Здоровье',
    published_date: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    author: {
      name: 'Доктор Сидоров',
      avatarUrl: 'https://randomuser.me/api/portraits/men/3.jpg',
    },
    source_url: 'https://example.com/article3',
  },
  {
    id: 4,
    title: 'Признаки здорового питомца',
    excerpt: 'Как понять, что ваш питомец здоров? Узнайте о ключевых признаках здоровья у собак и кошек, на что обращать внимание и когда стоит обратиться к ветеринару.',
    image_url: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=800',
    category: 'Здоровье',
    published_date: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    author: {
      name: 'Ветеринар Козлова',
      avatarUrl: 'https://randomuser.me/api/portraits/women/4.jpg',
    },
    source_url: 'https://example.com/article4',
  },
  {
    id: 5,
    title: 'Поведение кошек: что это значит?',
    excerpt: 'Понимание поведения кошек поможет лучше заботиться о вашем питомце. Разбираемся в языке тела, звуках и привычках наших пушистых друзей.',
    image_url: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800',
    category: 'Поведение',
    published_date: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    author: {
      name: 'Зоопсихолог Новикова',
      avatarUrl: 'https://randomuser.me/api/portraits/women/5.jpg',
    },
    source_url: 'https://example.com/article5',
  },
];

export const mockReminders = [
  {
    id: 1,
    animalName: 'Рекс',
    assistant_sms: 'Плановый осмотр у ветеринара',
    date_assistant: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: true,
  },
  {
    id: 2,
    animalName: 'Рекс',
    assistant_sms: 'Ревакцинация',
    date_assistant: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: true,
  },
  {
    id: 3,
    animalName: 'Мурка',
    assistant_sms: 'Дегельминтизация',
    date_assistant: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: true,
  },
  {
    id: 4,
    animalName: 'Рекс',
    assistant_sms: 'Купить корм',
    date_assistant: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: true,
  },
  {
    id: 5,
    animalName: 'Мурка',
    assistant_sms: 'Плановый осмотр',
    date_assistant: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    status: false,
  },
];

export const mockProducts = [
  {
    id: 1,
    name_ru: 'Амоксициллин 250мг',
    name_kg: 'Амоксициллин 250мг',
    is_active: true,
    img_url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
    description: 'Антибактериальный препарат широкого спектра действия для лечения инфекций у собак и кошек.',
    price: '850',
    stock_quantity: 25,
    subcategory_id: 1,
  },
  {
    id: 2,
    name_ru: 'Сухой корм для собак премиум класса',
    name_kg: 'Иттер үчүн премиум классты кургак азык',
    is_active: true,
    img_url: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=400',
    description: 'Полнорационный сухой корм для взрослых собак всех пород. Содержит натуральное мясо, овощи и витамины.',
    price: '2500',
    stock_quantity: 50,
    subcategory_id: 2,
  },
  {
    id: 3,
    name_ru: 'Корм для кошек с лососем',
    name_kg: 'Лосос менен мышык азыгы',
    is_active: true,
    img_url: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400',
    description: 'Влажный корм для кошек с натуральным лососем. Богат омега-3 жирными кислотами.',
    price: '450',
    stock_quantity: 30,
    subcategory_id: 3,
  },
  {
    id: 4,
    name_ru: "Игрушка для собак 'Мяч'",
    name_kg: "Иттер үчүн оюнчук 'Топ'",
    is_active: true,
    img_url: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400',
    description: 'Прочная резиновая игрушка для активных игр с собакой. Безопасна для зубов.',
    price: '350',
    stock_quantity: 15,
    subcategory_id: 4,
  },
  {
    id: 5,
    name_ru: 'Наполнитель для кошачьего туалета',
    name_kg: 'Мышык туалети үчүн толтуруучу',
    is_active: true,
    img_url: 'https://images.unsplash.com/photo-1545529468-42764ef8c85f?w=400',
    description: 'Древесный наполнитель с отличной впитываемостью и нейтрализацией запахов.',
    price: '800',
    stock_quantity: 40,
    subcategory_id: 5,
  },
];

export const mockCategories = [
  { id: 1, name_ru: 'Лекарства', name_kg: 'Дарылар', is_active: true },
  { id: 2, name_ru: 'Корм', name_kg: 'Азык', is_active: true },
  { id: 3, name_ru: 'Игрушки', name_kg: 'Оюнчуктар', is_active: true },
  { id: 4, name_ru: 'Аксессуары', name_kg: 'Аксессуарлар', is_active: true },
];

export const mockSubcategories = [
  { id: 1, name_ru: 'Антибиотики', name_kg: 'Антибиотиктер', category_id: 1, is_active: true },
  { id: 2, name_ru: 'Сухой корм', name_kg: 'Кургак азык', category_id: 2, is_active: true },
  { id: 3, name_ru: 'Влажный корм', name_kg: 'Нымдуу азык', category_id: 2, is_active: true },
  { id: 4, name_ru: 'Мячи', name_kg: 'Топтор', category_id: 3, is_active: true },
  { id: 5, name_ru: 'Наполнители', name_kg: 'Толтуруучулар', category_id: 4, is_active: true },
];

export const mockVetPatients = [
  {
    id: 1,
    pet_name: 'Рекс',
    owner_name: 'Иван Петров',
    owner_phone: '+996 (555) 123-45-67',
    species: 'Собака',
    breed: 'Немецкая овчарка',
    last_visit: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 2,
    pet_name: 'Мурка',
    owner_name: 'Иван Петров',
    owner_phone: '+996 (555) 123-45-67',
    species: 'Кошка',
    breed: 'Британская короткошерстная',
    last_visit: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
];

export const mockVetAppointments = [
  {
    id: 1,
    pet_owner_name: 'Иван Петров',
    pet_name: 'Рекс',
    appointment_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    reason: 'Плановый осмотр',
    status: 'confirmed',
    notes: null,
  },
  {
    id: 2,
    pet_owner_name: 'Иван Петров',
    pet_name: 'Рекс',
    appointment_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    reason: 'Вакцинация',
    status: 'pending',
    notes: null,
  },
  {
    id: 3,
    pet_owner_name: 'Иван Петров',
    pet_name: 'Мурка',
    appointment_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    reason: 'Консультация по питанию',
    status: 'completed',
    notes: 'Рекомендовано перейти на специальный корм',
  },
];

export const mockVetConsultations = [
  {
    id: 1,
    pet_owner_name: 'Иван Петров',
    pet_name: 'Рекс',
    question: 'Мой питомец стал вялым и плохо ест. Что делать?',
    answer: 'Рекомендую записаться на осмотр. Возможно, это признаки заболевания. До визита обеспечьте покой и доступ к воде.',
    status: 'answered',
    answered_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    pet_owner_name: 'Иван Петров',
    pet_name: 'Мурка',
    question: 'Как часто нужно делать прививки собаке?',
    answer: null,
    status: 'pending',
    answered_at: null,
  },
  {
    id: 3,
    pet_owner_name: 'Иван Петров',
    pet_name: 'Рекс',
    question: 'Можно ли давать кошке молоко?',
    answer: 'Взрослым кошкам молоко не рекомендуется, так как у многих развивается непереносимость лактозы. Лучше использовать специальные молочные продукты для кошек.',
    status: 'answered',
    answered_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockVetArticles = [
  {
    id: 1,
    title: 'Как правильно ухаживать за собакой в зимний период',
    content: 'Зима - особое время для наших питомцев. Важно обеспечить правильный уход...',
    excerpt: 'Советы по уходу за собакой в холодное время года',
    image_url: 'https://images.unsplash.com/photo-1551717743-49959800b1f6?w=800',
    category: 'Уход',
    is_published: true,
    views_count: 125,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    title: 'Признаки заболеваний у кошек',
    content: 'Владельцы кошек должны знать основные признаки заболеваний...',
    excerpt: 'На что обратить внимание, чтобы вовремя заметить болезнь',
    image_url: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800',
    category: 'Здоровье',
    is_published: true,
    views_count: 89,
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    title: 'Правильное питание для щенков',
    content: 'Питание щенков требует особого внимания...',
    excerpt: 'Рекомендации по кормлению щенков',
    image_url: null,
    category: 'Питание',
    is_published: false,
    views_count: 0,
    created_at: new Date().toISOString(),
  },
];

